# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s1343ytQ0h7qrzYWG7YtHGq8BoKVJaWX
"""

!pip install openai

import openai
openai.api_key = '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'
completion = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[{"role": "user", "content": "Hãy đề xuất 5 chủ đề tiểu luận cho môn học git và github"}]
)
print(completion['choices'][0]['message']['content'])